service: clicks-tracker-api

frameworkVersion: "2"

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

custom: ${{file(../../serverless.common.yml):custom}}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"
  stage: predev
  profile: ${{self:custom.profiles.${{self:custom.stage}}}}
  region: us-east-1

functions:
  hello:
    handler: handler.hello
