service: clicks-tracker-api

frameworkVersion: "2"

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

custom: ${{file(../../serverless.common.yml):custom}}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"
  stage: predev
  profile: ${{self:custom.profiles.${{self:custom.stage}}}}
  region: us-east-1

  environment:
    trackerTable: ${{self:custom.stage}}-clicksTracker

functions:
  trackLink:
    handler: src/api/trackLink.main
    events:
      - http:
          path: trackLink/{proxy+}
          method: get
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          - logs:CreateLogGroup
        Resource: "*"
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
          - dynamodb:updateItem
        Resource:
          - Fn::ImportValue: ${{self:custom.stage}}-clicksTracker
